// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_renewal
NumericVector simulate_renewal(std::vector<double> time_vec, std::vector<double> modulant_vec, double sigma, double Q);
RcppExport SEXP _BlinkR_simulate_renewal(SEXP time_vecSEXP, SEXP modulant_vecSEXP, SEXP sigmaSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type time_vec(time_vecSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type modulant_vec(modulant_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_renewal(time_vec, modulant_vec, sigma, Q));
    return rcpp_result_gen;
END_RCPP
}
// simulate_renewal_orig
NumericVector simulate_renewal_orig(std::vector<double> time_vec, std::vector<double> modulant_vec, double shape, double k);
RcppExport SEXP _BlinkR_simulate_renewal_orig(SEXP time_vecSEXP, SEXP modulant_vecSEXP, SEXP shapeSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type time_vec(time_vecSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type modulant_vec(modulant_vecSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_renewal_orig(time_vec, modulant_vec, shape, k));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_stan_fit4hsgp_multi_group_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4hsgp_one_group_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4hsgp_one_ind_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4prior_pc_one_group_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_BlinkR_simulate_renewal", (DL_FUNC) &_BlinkR_simulate_renewal, 4},
    {"_BlinkR_simulate_renewal_orig", (DL_FUNC) &_BlinkR_simulate_renewal_orig, 4},
    {"_rcpp_module_boot_stan_fit4hsgp_multi_group_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4hsgp_multi_group_mod, 0},
    {"_rcpp_module_boot_stan_fit4hsgp_one_group_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4hsgp_one_group_mod, 0},
    {"_rcpp_module_boot_stan_fit4hsgp_one_ind_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4hsgp_one_ind_mod, 0},
    {"_rcpp_module_boot_stan_fit4prior_pc_one_group_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4prior_pc_one_group_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BlinkR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
