// Generated by rstantools.  Do not edit by hand.

/*
    BlinkR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BlinkR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BlinkR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_hsgp_one_ind_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 172> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 108, column 2 to column 14)",
  " (in 'string', line 109, column 2 to column 20)",
  " (in 'string', line 110, column 2 to column 22)",
  " (in 'string', line 112, column 2 to column 10)",
  " (in 'string', line 116, column 2 to column 39)",
  " (in 'string', line 117, column 2 to column 47)",
  " (in 'string', line 118, column 2 to column 52)",
  " (in 'string', line 119, column 2 to column 67)",
  " (in 'string', line 123, column 2 to column 19)",
  " (in 'string', line 135, column 2 to column 31)",
  " (in 'string', line 133, column 4 to column 43)",
  " (in 'string', line 132, column 26 to line 134, column 3)",
  " (in 'string', line 132, column 9 to line 134, column 3)",
  " (in 'string', line 131, column 4 to column 45)",
  " (in 'string', line 130, column 26 to line 132, column 3)",
  " (in 'string', line 130, column 9 to line 134, column 3)",
  " (in 'string', line 129, column 4 to column 45)",
  " (in 'string', line 128, column 26 to line 130, column 3)",
  " (in 'string', line 128, column 9 to line 134, column 3)",
  " (in 'string', line 127, column 4 to column 45)",
  " (in 'string', line 126, column 26 to line 128, column 3)",
  " (in 'string', line 126, column 9 to line 134, column 3)",
  " (in 'string', line 125, column 4 to column 39)",
  " (in 'string', line 124, column 19 to line 126, column 3)",
  " (in 'string', line 124, column 2 to line 134, column 3)",
  " (in 'string', line 139, column 2 to column 19)",
  " (in 'string', line 140, column 2 to column 67)",
  " (in 'string', line 141, column 2 to column 70)",
  " (in 'string', line 142, column 2 to column 68)",
  " (in 'string', line 143, column 22 to line 144, column 48)",
  " (in 'string', line 143, column 2 to line 144, column 48)",
  " (in 'string', line 145, column 26 to line 146, column 56)",
  " (in 'string', line 145, column 2 to line 146, column 56)",
  " (in 'string', line 147, column 33 to line 148, column 70)",
  " (in 'string', line 147, column 2 to line 148, column 70)",
  " (in 'string', line 149, column 36 to line 150, column 76)",
  " (in 'string', line 149, column 2 to line 150, column 76)",
  " (in 'string', line 151, column 18 to column 25)",
  " (in 'string', line 151, column 2 to column 36)",
  " (in 'string', line 153, column 11 to column 18)",
  " (in 'string', line 153, column 4 to column 43)",
  " (in 'string', line 154, column 4 to column 25)",
  " (in 'string', line 152, column 17 to line 155, column 3)",
  " (in 'string', line 152, column 2 to line 155, column 3)",
  " (in 'string', line 157, column 4 to column 25)",
  " (in 'string', line 180, column 8 to column 41)",
  " (in 'string', line 181, column 8 to column 81)",
  " (in 'string', line 179, column 21 to line 182, column 7)",
  " (in 'string', line 179, column 6 to line 182, column 7)",
  " (in 'string', line 178, column 28 to line 183, column 5)",
  " (in 'string', line 178, column 11 to line 183, column 5)",
  " (in 'string', line 175, column 8 to column 41)",
  " (in 'string', line 176, column 8 to column 93)",
  " (in 'string', line 174, column 21 to line 177, column 7)",
  " (in 'string', line 174, column 6 to line 177, column 7)",
  " (in 'string', line 173, column 28 to line 178, column 5)",
  " (in 'string', line 173, column 11 to line 183, column 5)",
  " (in 'string', line 170, column 8 to column 41)",
  " (in 'string', line 171, column 8 to column 74)",
  " (in 'string', line 169, column 21 to line 172, column 7)",
  " (in 'string', line 169, column 6 to line 172, column 7)",
  " (in 'string', line 168, column 28 to line 173, column 5)",
  " (in 'string', line 168, column 11 to line 183, column 5)",
  " (in 'string', line 165, column 8 to column 41)",
  " (in 'string', line 166, column 8 to column 73)",
  " (in 'string', line 164, column 21 to line 167, column 7)",
  " (in 'string', line 164, column 6 to line 167, column 7)",
  " (in 'string', line 163, column 28 to line 168, column 5)",
  " (in 'string', line 163, column 11 to line 183, column 5)",
  " (in 'string', line 160, column 8 to column 41)",
  " (in 'string', line 161, column 8 to column 73)",
  " (in 'string', line 159, column 21 to line 162, column 7)",
  " (in 'string', line 159, column 6 to line 162, column 7)",
  " (in 'string', line 158, column 21 to line 163, column 5)",
  " (in 'string', line 158, column 4 to line 183, column 5)",
  " (in 'string', line 184, column 4 to column 38)",
  " (in 'string', line 156, column 23 to line 185, column 3)",
  " (in 'string', line 156, column 2 to line 185, column 3)",
  " (in 'string', line 71, column 2 to column 17)",
  " (in 'string', line 72, column 2 to column 24)",
  " (in 'string', line 73, column 8 to column 16)",
  " (in 'string', line 73, column 2 to column 32)",
  " (in 'string', line 74, column 9 to column 17)",
  " (in 'string', line 74, column 2 to column 33)",
  " (in 'string', line 75, column 2 to column 31)",
  " (in 'string', line 76, column 2 to column 31)",
  " (in 'string', line 77, column 2 to column 25)",
  " (in 'string', line 78, column 2 to column 41)",
  " (in 'string', line 79, column 2 to column 45)",
  " (in 'string', line 80, column 2 to column 52)",
  " (in 'string', line 81, column 2 to column 55)",
  " (in 'string', line 83, column 2 to column 23)",
  " (in 'string', line 84, column 9 to column 16)",
  " (in 'string', line 84, column 2 to column 23)",
  " (in 'string', line 85, column 9 to column 16)",
  " (in 'string', line 85, column 2 to column 21)",
  " (in 'string', line 88, column 2 to column 32)",
  " (in 'string', line 90, column 2 to line 93, column 20)",
  " (in 'string', line 94, column 2 to line 97, column 18)",
  " (in 'string', line 98, column 2 to column 29)",
  " (in 'string', line 100, column 18 to column 25)",
  " (in 'string', line 100, column 27 to column 28)",
  " (in 'string', line 100, column 2 to column 39)",
  " (in 'string', line 102, column 11 to column 18)",
  " (in 'string', line 102, column 4 to column 56)",
  " (in 'string', line 103, column 4 to column 42)",
  " (in 'string', line 101, column 17 to line 104, column 3)",
  " (in 'string', line 101, column 2 to line 104, column 3)",
  " (in 'string', line 108, column 9 to column 10)",
  " (in 'string', line 116, column 18 to column 35)",
  " (in 'string', line 117, column 18 to column 39)",
  " (in 'string', line 118, column 9 to column 37)",
  " (in 'string', line 119, column 18 to column 49)",
  " (in 'string', line 123, column 9 to column 10)",
  " (in 'string', line 135, column 9 to column 10)",
  " (in 'string', line 4, column 11 to column 12)",
  " (in 'string', line 4, column 14 to column 15)",
  " (in 'string', line 4, column 4 to column 21)",
  " (in 'string', line 6, column 6 to column 65)",
  " (in 'string', line 5, column 19 to line 7, column 5)",
  " (in 'string', line 5, column 4 to line 7, column 5)",
  " (in 'string', line 8, column 4 to column 15)",
  " (in 'string', line 3, column 45 to line 9, column 3)",
  " (in 'string', line 12, column 11 to column 12)",
  " (in 'string', line 12, column 4 to column 50)",
  " (in 'string', line 13, column 4 to column 44)",
  " (in 'string', line 11, column 37 to line 14, column 3)",
  " (in 'string', line 18, column 11 to column 12)",
  " (in 'string', line 18, column 4 to line 19, column 80)",
  " (in 'string', line 20, column 4 to column 38)",
  " (in 'string', line 17, column 63 to line 21, column 3)",
  " (in 'string', line 24, column 4 to column 50)",
  " (in 'string', line 25, column 11 to column 12)",
  " (in 'string', line 25, column 4 to column 60)",
  " (in 'string', line 26, column 4 to column 27)",
  " (in 'string', line 23, column 63 to line 27, column 3)",
  " (in 'string', line 30, column 4 to column 45)",
  " (in 'string', line 31, column 11 to column 12)",
  " (in 'string', line 31, column 4 to column 72)",
  " (in 'string', line 32, column 4 to column 41)",
  " (in 'string', line 29, column 63 to line 33, column 3)",
  " (in 'string', line 36, column 4 to column 29)",
  " (in 'string', line 37, column 11 to column 12)",
  " (in 'string', line 37, column 4 to column 50)",
  " (in 'string', line 38, column 11 to column 12)",
  " (in 'string', line 38, column 4 to line 41, column 6)",
  " (in 'string', line 42, column 4 to column 28)",
  " (in 'string', line 35, column 55 to line 43, column 3)",
  " (in 'string', line 46, column 4 to column 53)",
  " (in 'string', line 47, column 4 to column 51)",
  " (in 'string', line 48, column 4 to column 64)",
  " (in 'string', line 45, column 57 to line 49, column 3)",
  " (in 'string', line 52, column 6 to column 33)",
  " (in 'string', line 51, column 18 to line 53, column 5)",
  " (in 'string', line 51, column 4 to line 53, column 5)",
  " (in 'string', line 54, column 4 to column 119)",
  " (in 'string', line 55, column 4 to column 19)",
  " (in 'string', line 50, column 61 to line 56, column 3)",
  " (in 'string', line 65, column 6 to column 79)",
  " (in 'string', line 64, column 26 to line 66, column 5)",
  " (in 'string', line 64, column 11 to line 66, column 5)",
  " (in 'string', line 63, column 6 to column 48)",
  " (in 'string', line 62, column 26 to line 64, column 5)",
  " (in 'string', line 62, column 11 to line 66, column 5)",
  " (in 'string', line 61, column 6 to column 51)",
  " (in 'string', line 60, column 26 to line 62, column 5)",
  " (in 'string', line 60, column 11 to line 66, column 5)",
  " (in 'string', line 59, column 6 to column 48)",
  " (in 'string', line 58, column 19 to line 60, column 5)",
  " (in 'string', line 58, column 4 to line 66, column 5)",
  " (in 'string', line 57, column 67 to line 67, column 3)"};
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T2__, stan::base_type_t<T3__>>,-1,-1>
phi(const int& N, const int& M, const T2__& L, const T3__& x_arg__,
    std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T1__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T1__>,-1,1>
basis_indices(const int& M, const T1__& L, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern12(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern32(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern52(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__>,-1,1>
diagSPD_Periodic(const T0__& alpha, const T1__& rho, const int& M,
                 std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_EQ(const T0__& alpha, const T1__& rho, const int& M, const T3__& L,
           std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
gengamma_lpdf(const T0__& x, const T1__& shape, const T2__& k, const T3__&
              scale, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__, typename T_lp__, typename T_lp_accum__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
void
apply_prior_lp(const T0__& param, const T1__& dist, const T2__& arg1,
               const T3__& arg2, T_lp__& lp__, T_lp_accum__& lp_accum__,
               std::ostream* pstream__);
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T2__, stan::base_type_t<T3__>>,-1,-1>
phi(const int& N, const int& M, const T2__& L, const T3__& x_arg__,
    std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__,
                             stan::base_type_t<T3__>>;
  int current_statement__ = 0;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 116;
    stan::math::validate_non_negative_index("res", "N", N);
    current_statement__ = 117;
    stan::math::validate_non_negative_index("res", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,-1> res =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, M, DUMMY_VAR__);
    current_statement__ = 121;
    for (int m = 1; m <= M; ++m) {
      current_statement__ = 119;
      stan::model::assign(res,
        stan::math::multiply(stan::math::inv_sqrt(L),
          stan::math::sin(
            stan::math::divide(
              stan::math::multiply((stan::math::pi() * m),
                stan::math::add(x, L)), (2 * L)))), "assigning variable res",
        stan::model::index_omni(), stan::model::index_uni(m));
    }
    current_statement__ = 122;
    return res;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__, stan::require_all_t<stan::is_stan_scalar<T1__>>*>
Eigen::Matrix<stan::promote_args_t<T1__>,-1,1>
basis_indices(const int& M, const T1__& L, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 124;
    stan::math::validate_non_negative_index("indices", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> indices =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 125;
    stan::model::assign(indices, stan::math::linspaced_vector(M, 1, M),
      "assigning variable indices");
    current_statement__ = 126;
    return stan::math::square(
             stan::math::multiply((stan::math::pi() / (2 * L)), indices));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern12(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 128;
    stan::math::validate_non_negative_index("denom", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> denom =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 129;
    stan::model::assign(denom,
      stan::math::multiply(rho,
        stan::math::add(stan::math::square(stan::math::inv(rho)),
          stan::math::square(
            stan::math::multiply((stan::math::pi() / (2 * L)),
              basis_indices(M, L, pstream__))))), "assigning variable denom");
    current_statement__ = 130;
    return stan::math::multiply(alpha,
             stan::math::sqrt(stan::math::elt_divide(2.0, denom)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern32(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ factor = DUMMY_VAR__;
    current_statement__ = 132;
    factor = ((2 * alpha) *
      stan::math::pow((stan::math::sqrt(3) / rho), 1.5));
    current_statement__ = 133;
    stan::math::validate_non_negative_index("denom", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> denom =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 134;
    stan::model::assign(denom,
      stan::math::add((3 / stan::math::square(rho)),
        basis_indices(M, L, pstream__)), "assigning variable denom");
    current_statement__ = 135;
    return stan::math::elt_divide(factor, denom);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern52(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ factor = DUMMY_VAR__;
    current_statement__ = 137;
    factor = (16 * stan::math::pow((stan::math::sqrt(5) / rho), 5));
    current_statement__ = 138;
    stan::math::validate_non_negative_index("denom", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> denom =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 139;
    stan::model::assign(denom,
      stan::math::multiply(3,
        stan::math::pow(
          stan::math::add((5 / stan::math::square(rho)),
            basis_indices(M, L, pstream__)), 3)), "assigning variable denom");
    current_statement__ = 140;
    return stan::math::multiply(alpha,
             stan::math::sqrt(stan::math::elt_divide(factor, denom)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__>,-1,1>
diagSPD_Periodic(const T0__& alpha, const T1__& rho, const int& M,
                 std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ a = DUMMY_VAR__;
    current_statement__ = 142;
    a = stan::math::inv_square(rho);
    current_statement__ = 143;
    stan::math::validate_non_negative_index("indices", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> indices =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 144;
    stan::model::assign(indices, stan::math::linspaced_vector(M, 1, M),
      "assigning variable indices");
    current_statement__ = 145;
    stan::math::validate_non_negative_index("q", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> q =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 146;
    stan::model::assign(q,
      stan::math::exp(
        stan::math::add(stan::math::log(alpha),
          stan::math::multiply(0.5,
            stan::math::add((stan::math::log(2) - a),
              stan::math::to_vector(
                stan::math::log_modified_bessel_first_kind(indices, a)))))),
      "assigning variable q");
    current_statement__ = 147;
    return stan::math::append_row(q, q);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_EQ(const T0__& alpha, const T1__& rho, const int& M, const T3__& L,
           std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ factor = DUMMY_VAR__;
    current_statement__ = 149;
    factor = (alpha *
      stan::math::sqrt((stan::math::sqrt((2 * stan::math::pi())) * rho)));
    local_scalar_t__ exponent = DUMMY_VAR__;
    current_statement__ = 150;
    exponent = (-0.25 *
      stan::math::pow((((rho * stan::math::pi()) / 2) / L), 2));
    current_statement__ = 151;
    return stan::math::multiply(factor,
             stan::math::exp(
               stan::math::multiply(exponent,
                 stan::math::square(basis_indices(M, L, pstream__)))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
gengamma_lpdf(const T0__& x, const T1__& shape, const T2__& k, const T3__&
              scale, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 155;
    if (stan::math::logical_lte(x, 0.0)) {
      current_statement__ = 153;
      return stan::math::negative_infinity();
    }
    local_scalar_t__ logdens = DUMMY_VAR__;
    current_statement__ = 156;
    logdens = ((((stan::math::log(shape) - stan::math::lgamma(k)) + (((shape
      * k) - 1.0) * stan::math::log(x))) - ((shape * k) *
      stan::math::log(scale))) - stan::math::pow((x / scale), shape));
    current_statement__ = 157;
    return logdens;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__, typename T_lp__, typename T_lp_accum__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
void
apply_prior_lp(const T0__& param, const T1__& dist, const T2__& arg1,
               const T3__& arg2, T_lp__& lp__, T_lp_accum__& lp_accum__,
               std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 170;
    if (stan::math::logical_eq(dist, 1)) {
      current_statement__ = 168;
      lp_accum__.add(stan::math::normal_lpdf<false>(param, arg1, arg2));
    } else {
      current_statement__ = 167;
      if (stan::math::logical_eq(dist, 2)) {
        current_statement__ = 165;
        lp_accum__.add(stan::math::lognormal_lpdf<false>(param, arg1, arg2));
      } else {
        current_statement__ = 164;
        if (stan::math::logical_eq(dist, 3)) {
          current_statement__ = 162;
          lp_accum__.add(stan::math::cauchy_lpdf<false>(param, arg1, arg2));
        } else {
          current_statement__ = 161;
          if (stan::math::logical_eq(dist, 4)) {
            current_statement__ = 159;
            lp_accum__.add((stan::math::exponential_lpdf<false>(param, arg1)
              - stan::math::exponential_lccdf(1.0, arg1)));
          }
        }
      }
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_hsgp_one_ind final : public model_base_crtp<model_hsgp_one_ind> {
private:
  int M;
  int N_params;
  std::vector<std::vector<double>> params;
  Eigen::Matrix<double,-1,1> distributions_data__;
  int kernel;
  int family;
  double L_factor;
  int include_k;
  int include_shape;
  int include_mu_lognormal;
  int include_sigma_lognormal;
  int N_total;
  Eigen::Matrix<double,-1,1> t_ev_data__;
  Eigen::Matrix<double,-1,1> dt_data__;
  double L;
  Eigen::Matrix<double,-1,1> qx_data__;
  Eigen::Matrix<double,-1,1> qw_data__;
  Eigen::Matrix<double,-1,1> log_qw_data__;
  std::vector<Eigen::Matrix<double,-1,-1>> PHI_quad;
  int k_1dim__;
  int shape_1dim__;
  int mu_lognormal_1dim__;
  int sigma_lognormal_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> distributions{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_ev{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> dt{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> qx{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> qw{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_qw{nullptr, 0};
public:
  ~model_hsgp_one_ind() {}
  model_hsgp_one_ind(stan::io::var_context& context__, unsigned int
                     random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_hsgp_one_ind_namespace::model_hsgp_one_ind";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 79;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 79;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 79;
      stan::math::check_greater_or_equal(function__, "M", M, 1);
      current_statement__ = 80;
      context__.validate_dims("data initialization", "N_params", "int",
        std::vector<size_t>{});
      N_params = std::numeric_limits<int>::min();
      current_statement__ = 80;
      N_params = context__.vals_i("N_params")[(1 - 1)];
      current_statement__ = 80;
      stan::math::check_greater_or_equal(function__, "N_params", N_params, 1);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("params", "N_params", N_params);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "params", "double",
        std::vector<size_t>{static_cast<size_t>(N_params),
          static_cast<size_t>(2)});
      params = std::vector<std::vector<double>>(N_params,
                 std::vector<double>(2,
                   std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> params_flat__;
        current_statement__ = 82;
        params_flat__ = context__.vals_r("params");
        current_statement__ = 82;
        pos__ = 1;
        current_statement__ = 82;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 82;
          for (int sym2__ = 1; sym2__ <= N_params; ++sym2__) {
            current_statement__ = 82;
            stan::model::assign(params, params_flat__[(pos__ - 1)],
              "assigning variable params", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 82;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 83;
      stan::math::validate_non_negative_index("distributions", "N_params",
        N_params);
      current_statement__ = 84;
      context__.validate_dims("data initialization", "distributions",
        "double", std::vector<size_t>{static_cast<size_t>(N_params)});
      distributions_data__ = Eigen::Matrix<double,-1,1>::Constant(N_params,
                               std::numeric_limits<double>::quiet_NaN());
      new (&distributions)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(distributions_data__.data(),
        N_params);
      {
        std::vector<local_scalar_t__> distributions_flat__;
        current_statement__ = 84;
        distributions_flat__ = context__.vals_r("distributions");
        current_statement__ = 84;
        pos__ = 1;
        current_statement__ = 84;
        for (int sym1__ = 1; sym1__ <= N_params; ++sym1__) {
          current_statement__ = 84;
          stan::model::assign(distributions, distributions_flat__[(pos__ -
            1)], "assigning variable distributions",
            stan::model::index_uni(sym1__));
          current_statement__ = 84;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 85;
      context__.validate_dims("data initialization", "kernel", "int",
        std::vector<size_t>{});
      kernel = std::numeric_limits<int>::min();
      current_statement__ = 85;
      kernel = context__.vals_i("kernel")[(1 - 1)];
      current_statement__ = 85;
      stan::math::check_greater_or_equal(function__, "kernel", kernel, 1);
      current_statement__ = 85;
      stan::math::check_less_or_equal(function__, "kernel", kernel, 4);
      current_statement__ = 86;
      context__.validate_dims("data initialization", "family", "int",
        std::vector<size_t>{});
      family = std::numeric_limits<int>::min();
      current_statement__ = 86;
      family = context__.vals_i("family")[(1 - 1)];
      current_statement__ = 86;
      stan::math::check_greater_or_equal(function__, "family", family, 1);
      current_statement__ = 86;
      stan::math::check_less_or_equal(function__, "family", family, 5);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "L_factor", "double",
        std::vector<size_t>{});
      L_factor = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 87;
      L_factor = context__.vals_r("L_factor")[(1 - 1)];
      current_statement__ = 87;
      stan::math::check_greater_or_equal(function__, "L_factor", L_factor, 0);
      current_statement__ = 88;
      context__.validate_dims("data initialization", "include_k", "int",
        std::vector<size_t>{});
      include_k = std::numeric_limits<int>::min();
      current_statement__ = 88;
      include_k = context__.vals_i("include_k")[(1 - 1)];
      current_statement__ = 88;
      stan::math::check_greater_or_equal(function__, "include_k", include_k,
        0);
      current_statement__ = 88;
      stan::math::check_less_or_equal(function__, "include_k", include_k,
        N_params);
      current_statement__ = 89;
      context__.validate_dims("data initialization", "include_shape", "int",
        std::vector<size_t>{});
      include_shape = std::numeric_limits<int>::min();
      current_statement__ = 89;
      include_shape = context__.vals_i("include_shape")[(1 - 1)];
      current_statement__ = 89;
      stan::math::check_greater_or_equal(function__, "include_shape",
        include_shape, 0);
      current_statement__ = 89;
      stan::math::check_less_or_equal(function__, "include_shape",
        include_shape, N_params);
      current_statement__ = 90;
      context__.validate_dims("data initialization", "include_mu_lognormal",
        "int", std::vector<size_t>{});
      include_mu_lognormal = std::numeric_limits<int>::min();
      current_statement__ = 90;
      include_mu_lognormal = context__.vals_i("include_mu_lognormal")[(1 -
        1)];
      current_statement__ = 90;
      stan::math::check_greater_or_equal(function__, "include_mu_lognormal",
        include_mu_lognormal, 0);
      current_statement__ = 90;
      stan::math::check_less_or_equal(function__, "include_mu_lognormal",
        include_mu_lognormal, N_params);
      current_statement__ = 91;
      context__.validate_dims("data initialization",
        "include_sigma_lognormal", "int", std::vector<size_t>{});
      include_sigma_lognormal = std::numeric_limits<int>::min();
      current_statement__ = 91;
      include_sigma_lognormal = context__.vals_i("include_sigma_lognormal")[(1
        - 1)];
      current_statement__ = 91;
      stan::math::check_greater_or_equal(function__,
        "include_sigma_lognormal", include_sigma_lognormal, 0);
      current_statement__ = 91;
      stan::math::check_less_or_equal(function__, "include_sigma_lognormal",
        include_sigma_lognormal, N_params);
      current_statement__ = 92;
      context__.validate_dims("data initialization", "N_total", "int",
        std::vector<size_t>{});
      N_total = std::numeric_limits<int>::min();
      current_statement__ = 92;
      N_total = context__.vals_i("N_total")[(1 - 1)];
      current_statement__ = 92;
      stan::math::check_greater_or_equal(function__, "N_total", N_total, 1);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("t_ev", "N_total", N_total);
      current_statement__ = 94;
      context__.validate_dims("data initialization", "t_ev", "double",
        std::vector<size_t>{static_cast<size_t>(N_total)});
      t_ev_data__ = Eigen::Matrix<double,-1,1>::Constant(N_total,
                      std::numeric_limits<double>::quiet_NaN());
      new (&t_ev) Eigen::Map<Eigen::Matrix<double,-1,1>>(t_ev_data__.data(),
        N_total);
      {
        std::vector<local_scalar_t__> t_ev_flat__;
        current_statement__ = 94;
        t_ev_flat__ = context__.vals_r("t_ev");
        current_statement__ = 94;
        pos__ = 1;
        current_statement__ = 94;
        for (int sym1__ = 1; sym1__ <= N_total; ++sym1__) {
          current_statement__ = 94;
          stan::model::assign(t_ev, t_ev_flat__[(pos__ - 1)],
            "assigning variable t_ev", stan::model::index_uni(sym1__));
          current_statement__ = 94;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 95;
      stan::math::validate_non_negative_index("dt", "N_total", N_total);
      current_statement__ = 96;
      context__.validate_dims("data initialization", "dt", "double",
        std::vector<size_t>{static_cast<size_t>(N_total)});
      dt_data__ = Eigen::Matrix<double,-1,1>::Constant(N_total,
                    std::numeric_limits<double>::quiet_NaN());
      new (&dt) Eigen::Map<Eigen::Matrix<double,-1,1>>(dt_data__.data(),
        N_total);
      {
        std::vector<local_scalar_t__> dt_flat__;
        current_statement__ = 96;
        dt_flat__ = context__.vals_r("dt");
        current_statement__ = 96;
        pos__ = 1;
        current_statement__ = 96;
        for (int sym1__ = 1; sym1__ <= N_total; ++sym1__) {
          current_statement__ = 96;
          stan::model::assign(dt, dt_flat__[(pos__ - 1)],
            "assigning variable dt", stan::model::index_uni(sym1__));
          current_statement__ = 96;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 97;
      L = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 97;
      L = (L_factor * stan::math::max(t_ev));
      current_statement__ = 98;
      qx_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                    std::numeric_limits<double>::quiet_NaN());
      new (&qx) Eigen::Map<Eigen::Matrix<double,-1,1>>(qx_data__.data(), 3);
      current_statement__ = 98;
      stan::model::assign(qx,
        (Eigen::Matrix<double,-1,1>(3) << 0.1127016654, 0.5, 0.8872983346).finished(),
        "assigning variable qx");
      current_statement__ = 99;
      qw_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                    std::numeric_limits<double>::quiet_NaN());
      new (&qw) Eigen::Map<Eigen::Matrix<double,-1,1>>(qw_data__.data(), 3);
      current_statement__ = 99;
      stan::model::assign(qw,
        (Eigen::Matrix<double,-1,1>(3) << (5.0 / 18.0), (8.0 / 18.0), (5.0 /
                                         18.0)).finished(),
        "assigning variable qw");
      current_statement__ = 100;
      log_qw_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                        std::numeric_limits<double>::quiet_NaN());
      new (&log_qw)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_qw_data__.data(), 3);
      current_statement__ = 100;
      stan::model::assign(log_qw, stan::math::log(qw),
        "assigning variable log_qw");
      current_statement__ = 101;
      stan::math::validate_non_negative_index("PHI_quad", "N_total", N_total);
      current_statement__ = 102;
      stan::math::validate_non_negative_index("PHI_quad", "M", M);
      current_statement__ = 103;
      PHI_quad = std::vector<Eigen::Matrix<double,-1,-1>>(3,
                   Eigen::Matrix<double,-1,-1>::Constant(N_total, M,
                     std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 108;
      for (int j = 1; j <= 3; ++j) {
        current_statement__ = 104;
        stan::math::validate_non_negative_index("t_quad", "N_total", N_total);
        Eigen::Matrix<double,-1,1> t_quad =
          Eigen::Matrix<double,-1,1>::Constant(N_total,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 105;
        stan::model::assign(t_quad,
          stan::math::subtract(t_ev,
            stan::math::elt_multiply((1.0 -
              stan::model::rvalue(qx, "qx", stan::model::index_uni(j))), dt)),
          "assigning variable t_quad");
        current_statement__ = 106;
        stan::model::assign(PHI_quad, phi(N_total, M, L, t_quad, pstream__),
          "assigning variable PHI_quad", stan::model::index_uni(j));
      }
      current_statement__ = 109;
      stan::math::validate_non_negative_index("z", "M", M);
      current_statement__ = 110;
      k_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 110;
      k_1dim__ = (include_k ? 1 : 0);
      current_statement__ = 110;
      stan::math::validate_non_negative_index("k", "include_k ? 1 : 0",
        k_1dim__);
      current_statement__ = 111;
      shape_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 111;
      shape_1dim__ = (include_shape ? 1 : 0);
      current_statement__ = 111;
      stan::math::validate_non_negative_index("shape",
        "include_shape ? 1 : 0", shape_1dim__);
      current_statement__ = 112;
      mu_lognormal_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 112;
      mu_lognormal_1dim__ = (include_mu_lognormal ? 1 : 0);
      current_statement__ = 112;
      stan::math::validate_non_negative_index("mu_lognormal",
        "include_mu_lognormal ? 1 : 0", mu_lognormal_1dim__);
      current_statement__ = 113;
      sigma_lognormal_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 113;
      sigma_lognormal_1dim__ = (include_sigma_lognormal ? 1 : 0);
      current_statement__ = 113;
      stan::math::validate_non_negative_index("sigma_lognormal",
        "include_sigma_lognormal ? 1 : 0", sigma_lognormal_1dim__);
      current_statement__ = 114;
      stan::math::validate_non_negative_index("diag_S", "M", M);
      current_statement__ = 115;
      stan::math::validate_non_negative_index("beta", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = M + 1 + 1 + 1 + k_1dim__ + shape_1dim__ +
      mu_lognormal_1dim__ + sigma_lognormal_1dim__;
  }
  inline std::string model_name() const final {
    return "model_hsgp_one_ind";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_hsgp_one_ind_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 1;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 2;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 3;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 4;
      mu = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> k =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(k_1dim__, DUMMY_VAR__);
      current_statement__ = 5;
      k = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1, lp__,
            k_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> shape =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(shape_1dim__,
          DUMMY_VAR__);
      current_statement__ = 6;
      shape = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1, lp__,
                shape_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> mu_lognormal =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(mu_lognormal_1dim__,
          DUMMY_VAR__);
      current_statement__ = 7;
      mu_lognormal = in__.template read<
                       Eigen::Matrix<local_scalar_t__,-1,1>>(mu_lognormal_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_lognormal =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(sigma_lognormal_1dim__,
          DUMMY_VAR__);
      current_statement__ = 8;
      sigma_lognormal = in__.template read_constrain_lb<
                          Eigen::Matrix<local_scalar_t__,-1,1>,
                          jacobian__>(0, lp__, sigma_lognormal_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> diag_S =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 25;
      if (stan::math::logical_eq(kernel, 1)) {
        current_statement__ = 23;
        stan::model::assign(diag_S, diagSPD_EQ(alpha, rho, M, L, pstream__),
          "assigning variable diag_S");
      } else {
        current_statement__ = 22;
        if (stan::math::logical_eq(kernel, 2)) {
          current_statement__ = 20;
          stan::model::assign(diag_S,
            diagSPD_Matern12(alpha, rho, M, L, pstream__),
            "assigning variable diag_S");
        } else {
          current_statement__ = 19;
          if (stan::math::logical_eq(kernel, 3)) {
            current_statement__ = 17;
            stan::model::assign(diag_S,
              diagSPD_Matern32(alpha, rho, M, L, pstream__),
              "assigning variable diag_S");
          } else {
            current_statement__ = 16;
            if (stan::math::logical_eq(kernel, 4)) {
              current_statement__ = 14;
              stan::model::assign(diag_S,
                diagSPD_Matern52(alpha, rho, M, L, pstream__),
                "assigning variable diag_S");
            } else {
              current_statement__ = 13;
              if (stan::math::logical_eq(kernel, 5)) {
                current_statement__ = 11;
                stan::model::assign(diag_S,
                  diagSPD_Periodic(alpha, rho, M, pstream__),
                  "assigning variable diag_S");
              }
            }
          }
        }
      }
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(beta, stan::math::elt_multiply(diag_S, z),
        "assigning variable beta");
      {
        current_statement__ = 26;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z));
        current_statement__ = 27;
        apply_prior_lp<propto__>(mu,
          stan::model::rvalue(distributions, "distributions",
            stan::model::index_uni(1)),
          stan::model::rvalue(params, "params", stan::model::index_uni(1),
            stan::model::index_uni(1)),
          stan::model::rvalue(params, "params", stan::model::index_uni(1),
            stan::model::index_uni(2)), lp__, lp_accum__, pstream__);
        current_statement__ = 28;
        apply_prior_lp<propto__>(alpha,
          stan::model::rvalue(distributions, "distributions",
            stan::model::index_uni(2)),
          stan::model::rvalue(params, "params", stan::model::index_uni(2),
            stan::model::index_uni(1)),
          stan::model::rvalue(params, "params", stan::model::index_uni(2),
            stan::model::index_uni(2)), lp__, lp_accum__, pstream__);
        current_statement__ = 29;
        apply_prior_lp<propto__>(rho,
          stan::model::rvalue(distributions, "distributions",
            stan::model::index_uni(3)),
          stan::model::rvalue(params, "params", stan::model::index_uni(3),
            stan::model::index_uni(1)),
          stan::model::rvalue(params, "params", stan::model::index_uni(3),
            stan::model::index_uni(2)), lp__, lp_accum__, pstream__);
        current_statement__ = 31;
        if (stan::math::logical_neq(include_k, 0)) {
          current_statement__ = 30;
          apply_prior_lp<propto__>(
            stan::model::rvalue(k, "k", stan::model::index_uni(1)),
            stan::model::rvalue(distributions, "distributions",
              stan::model::index_uni(include_k)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_k), stan::model::index_uni(1)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_k), stan::model::index_uni(2)),
            lp__, lp_accum__, pstream__);
        }
        current_statement__ = 33;
        if (stan::math::logical_neq(include_shape, 0)) {
          current_statement__ = 32;
          apply_prior_lp<propto__>(
            stan::model::rvalue(shape, "shape", stan::model::index_uni(1)),
            stan::model::rvalue(distributions, "distributions",
              stan::model::index_uni(include_shape)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_shape),
              stan::model::index_uni(1)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_shape),
              stan::model::index_uni(2)), lp__, lp_accum__, pstream__);
        }
        current_statement__ = 35;
        if (stan::math::logical_neq(include_mu_lognormal, 0)) {
          current_statement__ = 34;
          apply_prior_lp<propto__>(
            stan::model::rvalue(mu_lognormal, "mu_lognormal",
              stan::model::index_uni(1)),
            stan::model::rvalue(distributions, "distributions",
              stan::model::index_uni(include_mu_lognormal)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_mu_lognormal),
              stan::model::index_uni(1)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_mu_lognormal),
              stan::model::index_uni(2)), lp__, lp_accum__, pstream__);
        }
        current_statement__ = 37;
        if (stan::math::logical_neq(include_sigma_lognormal, 0)) {
          current_statement__ = 36;
          apply_prior_lp<propto__>(
            stan::model::rvalue(sigma_lognormal, "sigma_lognormal",
              stan::model::index_uni(1)),
            stan::model::rvalue(distributions, "distributions",
              stan::model::index_uni(include_sigma_lognormal)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_sigma_lognormal),
              stan::model::index_uni(1)),
            stan::model::rvalue(params, "params",
              stan::model::index_uni(include_sigma_lognormal),
              stan::model::index_uni(2)), lp__, lp_accum__, pstream__);
        }
        current_statement__ = 38;
        stan::math::validate_non_negative_index("eta_quad", "N_total",
          N_total);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> eta_quad =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(3,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_total,
              DUMMY_VAR__));
        current_statement__ = 44;
        for (int j = 1; j <= 3; ++j) {
          current_statement__ = 40;
          stan::math::validate_non_negative_index("f", "N_total", N_total);
          Eigen::Matrix<local_scalar_t__,-1,1> f =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_total,
              DUMMY_VAR__);
          current_statement__ = 41;
          stan::model::assign(f,
            stan::math::multiply(
              stan::model::rvalue(PHI_quad, "PHI_quad",
                stan::model::index_uni(j)), beta), "assigning variable f");
          current_statement__ = 42;
          stan::model::assign(eta_quad, stan::math::add(mu, f),
            "assigning variable eta_quad", stan::model::index_uni(j));
        }
        current_statement__ = 78;
        for (int n = 1; n <= N_total; ++n) {
          Eigen::Matrix<local_scalar_t__,-1,1> log_kernel =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__);
          current_statement__ = 75;
          if (stan::math::logical_eq(family, 1)) {
            current_statement__ = 73;
            for (int j = 1; j <= 3; ++j) {
              local_scalar_t__ scale = DUMMY_VAR__;
              current_statement__ = 70;
              scale = stan::math::exp(
                        stan::model::rvalue(
                          stan::model::rvalue(eta_quad, "eta_quad",
                            stan::model::index_uni(j)), "eta_quad[j]",
                          stan::model::index_uni(n)));
              current_statement__ = 71;
              stan::model::assign(log_kernel,
                (stan::model::rvalue(log_qw, "log_qw",
                   stan::model::index_uni(j)) +
                stan::math::exponential_lpdf<false>(
                  stan::model::rvalue(dt, "dt", stan::model::index_uni(n)),
                  stan::math::inv(scale))), "assigning variable log_kernel",
                stan::model::index_uni(j));
            }
          } else {
            current_statement__ = 69;
            if (stan::math::logical_eq(family, 2)) {
              current_statement__ = 67;
              for (int j = 1; j <= 3; ++j) {
                local_scalar_t__ scale = DUMMY_VAR__;
                current_statement__ = 64;
                scale = stan::math::exp(
                          stan::model::rvalue(
                            stan::model::rvalue(eta_quad, "eta_quad",
                              stan::model::index_uni(j)), "eta_quad[j]",
                            stan::model::index_uni(n)));
                current_statement__ = 65;
                stan::model::assign(log_kernel,
                  (stan::model::rvalue(log_qw, "log_qw",
                     stan::model::index_uni(j)) +
                  stan::math::gamma_lpdf<false>(
                    stan::model::rvalue(dt, "dt", stan::model::index_uni(n)),
                    stan::model::rvalue(k, "k", stan::model::index_uni(1)),
                    stan::math::inv(scale))),
                  "assigning variable log_kernel", stan::model::index_uni(j));
              }
            } else {
              current_statement__ = 63;
              if (stan::math::logical_eq(family, 3)) {
                current_statement__ = 61;
                for (int j = 1; j <= 3; ++j) {
                  local_scalar_t__ scale = DUMMY_VAR__;
                  current_statement__ = 58;
                  scale = stan::math::exp(
                            stan::model::rvalue(
                              stan::model::rvalue(eta_quad, "eta_quad",
                                stan::model::index_uni(j)), "eta_quad[j]",
                              stan::model::index_uni(n)));
                  current_statement__ = 59;
                  stan::model::assign(log_kernel,
                    (stan::model::rvalue(log_qw, "log_qw",
                       stan::model::index_uni(j)) +
                    stan::math::weibull_lpdf<false>(
                      stan::model::rvalue(dt, "dt", stan::model::index_uni(n)),
                      stan::model::rvalue(shape, "shape",
                        stan::model::index_uni(1)), scale)),
                    "assigning variable log_kernel",
                    stan::model::index_uni(j));
                }
              } else {
                current_statement__ = 57;
                if (stan::math::logical_eq(family, 4)) {
                  current_statement__ = 55;
                  for (int j = 1; j <= 3; ++j) {
                    local_scalar_t__ scale = DUMMY_VAR__;
                    current_statement__ = 52;
                    scale = stan::math::exp(
                              stan::model::rvalue(
                                stan::model::rvalue(eta_quad, "eta_quad",
                                  stan::model::index_uni(j)), "eta_quad[j]",
                                stan::model::index_uni(n)));
                    current_statement__ = 53;
                    stan::model::assign(log_kernel,
                      (stan::model::rvalue(log_qw, "log_qw",
                         stan::model::index_uni(j)) +
                      stan::math::lognormal_lpdf<false>(
                        stan::model::rvalue(dt, "dt",
                          stan::model::index_uni(n)), mu_lognormal,
                        stan::model::rvalue(sigma_lognormal,
                          "sigma_lognormal", stan::model::index_uni(1)))),
                      "assigning variable log_kernel",
                      stan::model::index_uni(j));
                  }
                } else {
                  current_statement__ = 51;
                  if (stan::math::logical_eq(family, 5)) {
                    current_statement__ = 49;
                    for (int j = 1; j <= 3; ++j) {
                      local_scalar_t__ scale = DUMMY_VAR__;
                      current_statement__ = 46;
                      scale = stan::math::exp(
                                stan::model::rvalue(
                                  stan::model::rvalue(eta_quad, "eta_quad",
                                    stan::model::index_uni(j)),
                                  "eta_quad[j]", stan::model::index_uni(n)));
                      current_statement__ = 47;
                      stan::model::assign(log_kernel,
                        (stan::model::rvalue(log_qw, "log_qw",
                           stan::model::index_uni(j)) +
                        gengamma_lpdf<false>(
                          stan::model::rvalue(dt, "dt",
                            stan::model::index_uni(n)),
                          stan::model::rvalue(shape, "shape",
                            stan::model::index_uni(1)),
                          stan::model::rvalue(k, "k",
                            stan::model::index_uni(1)), scale, pstream__)),
                        "assigning variable log_kernel",
                        stan::model::index_uni(j));
                    }
                  }
                }
              }
            }
          }
          current_statement__ = 76;
          lp_accum__.add(stan::math::log_sum_exp(log_kernel));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_hsgp_one_ind_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> z =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M);
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      mu = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> k =
        Eigen::Matrix<double,-1,1>::Constant(k_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      k = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1, lp__,
            k_1dim__);
      Eigen::Matrix<double,-1,1> shape =
        Eigen::Matrix<double,-1,1>::Constant(shape_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      shape = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1, lp__,
                shape_1dim__);
      Eigen::Matrix<double,-1,1> mu_lognormal =
        Eigen::Matrix<double,-1,1>::Constant(mu_lognormal_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      mu_lognormal = in__.template read<
                       Eigen::Matrix<local_scalar_t__,-1,1>>(mu_lognormal_1dim__);
      Eigen::Matrix<double,-1,1> sigma_lognormal =
        Eigen::Matrix<double,-1,1>::Constant(sigma_lognormal_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 8;
      sigma_lognormal = in__.template read_constrain_lb<
                          Eigen::Matrix<local_scalar_t__,-1,1>,
                          jacobian__>(0, lp__, sigma_lognormal_1dim__);
      Eigen::Matrix<double,-1,1> diag_S =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(z);
      out__.write(rho);
      out__.write(alpha);
      out__.write(mu);
      out__.write(k);
      out__.write(shape);
      out__.write(mu_lognormal);
      out__.write(sigma_lognormal);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 25;
      if (stan::math::logical_eq(kernel, 1)) {
        current_statement__ = 23;
        stan::model::assign(diag_S, diagSPD_EQ(alpha, rho, M, L, pstream__),
          "assigning variable diag_S");
      } else {
        current_statement__ = 22;
        if (stan::math::logical_eq(kernel, 2)) {
          current_statement__ = 20;
          stan::model::assign(diag_S,
            diagSPD_Matern12(alpha, rho, M, L, pstream__),
            "assigning variable diag_S");
        } else {
          current_statement__ = 19;
          if (stan::math::logical_eq(kernel, 3)) {
            current_statement__ = 17;
            stan::model::assign(diag_S,
              diagSPD_Matern32(alpha, rho, M, L, pstream__),
              "assigning variable diag_S");
          } else {
            current_statement__ = 16;
            if (stan::math::logical_eq(kernel, 4)) {
              current_statement__ = 14;
              stan::model::assign(diag_S,
                diagSPD_Matern52(alpha, rho, M, L, pstream__),
                "assigning variable diag_S");
            } else {
              current_statement__ = 13;
              if (stan::math::logical_eq(kernel, 5)) {
                current_statement__ = 11;
                stan::model::assign(diag_S,
                  diagSPD_Periodic(alpha, rho, M, pstream__),
                  "assigning variable diag_S");
              }
            }
          }
        }
      }
      current_statement__ = 10;
      stan::model::assign(beta, stan::math::elt_multiply(diag_S, z),
        "assigning variable beta");
      if (emit_transformed_parameters__) {
        out__.write(diag_S);
        out__.write(beta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(M),
        "assigning variable z");
      out__.write(z);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 2;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, rho);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 3;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 4;
      mu = in__.read<local_scalar_t__>();
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> k =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(k_1dim__, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(k,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(k_1dim__),
        "assigning variable k");
      out__.write_free_lb(1, k);
      Eigen::Matrix<local_scalar_t__,-1,1> shape =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(shape_1dim__,
          DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(shape,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(shape_1dim__),
        "assigning variable shape");
      out__.write_free_lb(1, shape);
      Eigen::Matrix<local_scalar_t__,-1,1> mu_lognormal =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(mu_lognormal_1dim__,
          DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(mu_lognormal,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(mu_lognormal_1dim__),
        "assigning variable mu_lognormal");
      out__.write(mu_lognormal);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_lognormal =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(sigma_lognormal_1dim__,
          DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(sigma_lognormal,
        in__.read<
          Eigen::Matrix<local_scalar_t__,-1,1>>(sigma_lognormal_1dim__),
        "assigning variable sigma_lognormal");
      out__.write_free_lb(0, sigma_lognormal);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "z", "double",
        std::vector<size_t>{static_cast<size_t>(M)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "k", "double",
        std::vector<size_t>{static_cast<size_t>(k_1dim__)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "shape", "double",
        std::vector<size_t>{static_cast<size_t>(shape_1dim__)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "mu_lognormal",
        "double",
        std::vector<size_t>{static_cast<size_t>(mu_lognormal_1dim__)});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "sigma_lognormal",
        "double",
        std::vector<size_t>{static_cast<size_t>(sigma_lognormal_1dim__)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_flat__;
        current_statement__ = 1;
        z_flat__ = context__.vals_r("z");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(z, z_flat__[(pos__ - 1)],
            "assigning variable z", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 2;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lb(0, rho);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 3;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 4;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> k =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(k_1dim__, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> k_flat__;
        current_statement__ = 5;
        k_flat__ = context__.vals_r("k");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= k_1dim__; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(k, k_flat__[(pos__ - 1)],
            "assigning variable k", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(1, k);
      Eigen::Matrix<local_scalar_t__,-1,1> shape =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(shape_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> shape_flat__;
        current_statement__ = 6;
        shape_flat__ = context__.vals_r("shape");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= shape_1dim__; ++sym1__) {
          current_statement__ = 6;
          stan::model::assign(shape, shape_flat__[(pos__ - 1)],
            "assigning variable shape", stan::model::index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(1, shape);
      Eigen::Matrix<local_scalar_t__,-1,1> mu_lognormal =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(mu_lognormal_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_lognormal_flat__;
        current_statement__ = 7;
        mu_lognormal_flat__ = context__.vals_r("mu_lognormal");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= mu_lognormal_1dim__; ++sym1__) {
          current_statement__ = 7;
          stan::model::assign(mu_lognormal, mu_lognormal_flat__[(pos__ - 1)],
            "assigning variable mu_lognormal", stan::model::index_uni(sym1__));
          current_statement__ = 7;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(mu_lognormal);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_lognormal =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(sigma_lognormal_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_lognormal_flat__;
        current_statement__ = 8;
        sigma_lognormal_flat__ = context__.vals_r("sigma_lognormal");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= sigma_lognormal_1dim__; ++sym1__) {
          current_statement__ = 8;
          stan::model::assign(sigma_lognormal, sigma_lognormal_flat__[(pos__
            - 1)], "assigning variable sigma_lognormal",
            stan::model::index_uni(sym1__));
          current_statement__ = 8;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma_lognormal);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"z", "rho", "alpha", "mu", "k",
                "shape", "mu_lognormal", "sigma_lognormal"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"diag_S", "beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(M)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(k_1dim__)},
                std::vector<size_t>{static_cast<size_t>(shape_1dim__)},
                std::vector<size_t>{static_cast<size_t>(mu_lognormal_1dim__)},
                std::vector<size_t>{static_cast<size_t>(
                                      sigma_lognormal_1dim__)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(M)},
             std::vector<size_t>{static_cast<size_t>(M)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      param_names__.emplace_back(std::string() + "z" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho");
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "mu");
    for (int sym1__ = 1; sym1__ <= k_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "k" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= shape_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "shape" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= mu_lognormal_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_lognormal" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= sigma_lognormal_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_lognormal" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "diag_S" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      param_names__.emplace_back(std::string() + "z" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho");
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "mu");
    for (int sym1__ = 1; sym1__ <= k_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "k" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= shape_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "shape" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= mu_lognormal_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_lognormal" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= sigma_lognormal_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_lognormal" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "diag_S" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(k_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"shape\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(shape_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"mu_lognormal\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(mu_lognormal_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma_lognormal\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(sigma_lognormal_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"diag_S\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(k_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"shape\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(shape_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"mu_lognormal\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(mu_lognormal_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma_lognormal\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(sigma_lognormal_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"diag_S\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((M + 1) + 1) + 1) + k_1dim__) +
      shape_1dim__) + mu_lognormal_1dim__) + sigma_lognormal_1dim__);
    const size_t num_transformed = emit_transformed_parameters * ((M + M));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((M + 1) + 1) + 1) + k_1dim__) +
      shape_1dim__) + mu_lognormal_1dim__) + sigma_lognormal_1dim__);
    const size_t num_transformed = emit_transformed_parameters * ((M + M));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_hsgp_one_ind_namespace::model_hsgp_one_ind;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_hsgp_one_ind_namespace::profiles__;
}
#endif
#endif
