// Generated by rstantools.  Do not edit by hand.

/*
    BlinkR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BlinkR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BlinkR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_hsgp_updated_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 110> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 85, column 2 to column 18)",
  " (in 'string', line 86, column 2 to column 24)",
  " (in 'string', line 87, column 2 to column 26)",
  " (in 'string', line 89, column 2 to column 30)",
  " (in 'string', line 90, column 2 to column 25)",
  " (in 'string', line 91, column 2 to column 27)",
  " (in 'string', line 93, column 2 to column 15)",
  " (in 'string', line 97, column 2 to column 18)",
  " (in 'string', line 98, column 2 to column 29)",
  " (in 'string', line 102, column 2 to column 22)",
  " (in 'string', line 103, column 2 to column 59)",
  " (in 'string', line 104, column 2 to column 62)",
  " (in 'string', line 110, column 2 to column 47)",
  " (in 'string', line 111, column 2 to column 66)",
  " (in 'string', line 106, column 2 to column 35)",
  " (in 'string', line 108, column 4 to column 41)",
  " (in 'string', line 107, column 17 to line 109, column 3)",
  " (in 'string', line 107, column 2 to line 109, column 3)",
  " (in 'string', line 115, column 2 to column 23)",
  " (in 'string', line 116, column 2 to column 56)",
  " (in 'string', line 117, column 2 to column 38)",
  " (in 'string', line 118, column 2 to column 40)",
  " (in 'string', line 119, column 2 to column 31)",
  " (in 'string', line 120, column 2 to column 32)",
  " (in 'string', line 121, column 2 to column 20)",
  " (in 'string', line 123, column 2 to column 33)",
  " (in 'string', line 126, column 2 to column 39)",
  " (in 'string', line 126, column 34 to column 35)",
  " (in 'string', line 127, column 18 to column 25)",
  " (in 'string', line 127, column 2 to column 36)",
  " (in 'string', line 129, column 11 to column 18)",
  " (in 'string', line 129, column 4 to column 55)",
  " (in 'string', line 130, column 11 to column 18)",
  " (in 'string', line 130, column 4 to column 78)",
  " (in 'string', line 133, column 4 to column 44)",
  " (in 'string', line 128, column 17 to line 134, column 3)",
  " (in 'string', line 128, column 2 to line 134, column 3)",
  " (in 'string', line 136, column 4 to column 25)",
  " (in 'string', line 138, column 6 to column 40)",
  " (in 'string', line 139, column 6 to column 63)",
  " (in 'string', line 137, column 19 to line 140, column 5)",
  " (in 'string', line 137, column 4 to line 140, column 5)",
  " (in 'string', line 141, column 4 to column 38)",
  " (in 'string', line 135, column 23 to line 142, column 3)",
  " (in 'string', line 135, column 2 to line 142, column 3)",
  " (in 'string', line 46, column 2 to column 17)",
  " (in 'string', line 47, column 2 to column 23)",
  " (in 'string', line 48, column 2 to column 17)",
  " (in 'string', line 49, column 2 to column 27)",
  " (in 'string', line 50, column 2 to column 28)",
  " (in 'string', line 51, column 2 to column 25)",
  " (in 'string', line 52, column 9 to column 16)",
  " (in 'string', line 52, column 2 to column 23)",
  " (in 'string', line 53, column 9 to column 16)",
  " (in 'string', line 53, column 2 to column 21)",
  " (in 'string', line 54, column 8 to column 15)",
  " (in 'string', line 54, column 2 to line 55, column 31)",
  " (in 'string', line 58, column 2 to line 59, column 25)",
  " (in 'string', line 61, column 2 to line 64, column 20)",
  " (in 'string', line 65, column 2 to line 68, column 18)",
  " (in 'string', line 69, column 2 to column 29)",
  " (in 'string', line 71, column 18 to column 25)",
  " (in 'string', line 71, column 27 to column 28)",
  " (in 'string', line 71, column 2 to column 39)",
  " (in 'string', line 73, column 11 to column 18)",
  " (in 'string', line 73, column 4 to column 56)",
  " (in 'string', line 74, column 4 to line 80, column 8)",
  " (in 'string', line 72, column 17 to line 81, column 3)",
  " (in 'string', line 72, column 2 to line 81, column 3)",
  " (in 'string', line 85, column 9 to column 10)",
  " (in 'string', line 89, column 9 to column 14)",
  " (in 'string', line 89, column 16 to column 17)",
  " (in 'string', line 93, column 9 to column 10)",
  " (in 'string', line 102, column 9 to column 10)",
  " (in 'string', line 102, column 12 to column 13)",
  " (in 'string', line 103, column 9 to column 10)",
  " (in 'string', line 104, column 9 to column 10)",
  " (in 'string', line 110, column 9 to column 10)",
  " (in 'string', line 111, column 9 to column 10)",
  " (in 'string', line 111, column 12 to column 13)",
  " (in 'string', line 3, column 11 to column 12)",
  " (in 'string', line 3, column 14 to column 15)",
  " (in 'string', line 3, column 4 to column 21)",
  " (in 'string', line 5, column 6 to column 65)",
  " (in 'string', line 4, column 19 to line 6, column 5)",
  " (in 'string', line 4, column 4 to line 6, column 5)",
  " (in 'string', line 7, column 4 to column 15)",
  " (in 'string', line 2, column 45 to line 8, column 3)",
  " (in 'string', line 15, column 11 to column 12)",
  " (in 'string', line 15, column 4 to column 50)",
  " (in 'string', line 16, column 11 to column 12)",
  " (in 'string', line 16, column 4 to line 17, column 68)",
  " (in 'string', line 18, column 4 to column 42)",
  " (in 'string', line 14, column 4 to line 19, column 3)",
  " (in 'string', line 23, column 11 to column 12)",
  " (in 'string', line 23, column 4 to column 50)",
  " (in 'string', line 25, column 4 to column 44)",
  " (in 'string', line 22, column 4 to line 26, column 3)",
  " (in 'string', line 32, column 4 to column 50)",
  " (in 'string', line 33, column 11 to column 12)",
  " (in 'string', line 33, column 4 to column 61)",
  " (in 'string', line 34, column 2 to column 25)",
  " (in 'string', line 31, column 6 to line 35, column 3)",
  " (in 'string', line 38, column 11 to column 12)",
  " (in 'string', line 38, column 4 to column 50)",
  " (in 'string', line 39, column 4 to column 53)",
  " (in 'string', line 40, column 4 to column 51)",
  " (in 'string', line 41, column 4 to column 52)",
  " (in 'string', line 37, column 57 to line 42, column 1)"};
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T2__, stan::base_type_t<T3__>>,-1,-1>
phi(const int& N, const int& M, const T2__& L, const T3__& x_arg__,
    std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern12(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T1__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T1__>,-1,1>
matern_indices(const int& M, const T1__& L, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern32(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_EQ(const T0__& alpha, const T1__& rho, const int& M, const T3__& L,
           std::ostream* pstream__);
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T2__, stan::base_type_t<T3__>>,-1,-1>
phi(const int& N, const int& M, const T2__& L, const T3__& x_arg__,
    std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__,
                             stan::base_type_t<T3__>>;
  int current_statement__ = 0;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 81;
    stan::math::validate_non_negative_index("res", "N", N);
    current_statement__ = 82;
    stan::math::validate_non_negative_index("res", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,-1> res =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, M, DUMMY_VAR__);
    current_statement__ = 86;
    for (int m = 1; m <= M; ++m) {
      current_statement__ = 84;
      stan::model::assign(res,
        stan::math::multiply(stan::math::inv_sqrt(L),
          stan::math::sin(
            stan::math::divide(
              stan::math::multiply((stan::math::pi() * m),
                stan::math::add(x, L)), (2 * L)))), "assigning variable res",
        stan::model::index_omni(), stan::model::index_uni(m));
    }
    current_statement__ = 87;
    return res;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern12(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 89;
    stan::math::validate_non_negative_index("indices", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> indices =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 90;
    stan::model::assign(indices, stan::math::linspaced_vector(M, 1, M),
      "assigning variable indices");
    current_statement__ = 91;
    stan::math::validate_non_negative_index("denom", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> denom =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 92;
    stan::model::assign(denom,
      stan::math::multiply(rho,
        stan::math::add(stan::math::square(stan::math::inv(rho)),
          stan::math::square(
            stan::math::multiply((stan::math::pi() / (2 * L)), indices)))),
      "assigning variable denom");
    current_statement__ = 93;
    return stan::math::multiply(alpha,
             stan::math::sqrt(
               stan::math::multiply(2.0, stan::math::inv(denom))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__, stan::require_all_t<stan::is_stan_scalar<T1__>>*>
Eigen::Matrix<stan::promote_args_t<T1__>,-1,1>
matern_indices(const int& M, const T1__& L, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 95;
    stan::math::validate_non_negative_index("indices", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> indices =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 96;
    stan::model::assign(indices, stan::math::linspaced_vector(M, 1, M),
      "assigning variable indices");
    current_statement__ = 97;
    return stan::math::square(
             stan::math::multiply((stan::math::pi() / (2 * L)), indices));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_Matern32(const T0__& alpha, const T1__& rho, const int& M,
                 const T3__& L, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ factor = DUMMY_VAR__;
    current_statement__ = 99;
    factor = ((2 * alpha) *
      stan::math::pow((stan::math::sqrt(3) / rho), 1.5));
    current_statement__ = 100;
    stan::math::validate_non_negative_index("denom", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> denom =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 101;
    stan::model::assign(denom,
      stan::math::add((3 / stan::math::square(rho)),
        matern_indices(M, L, pstream__)), "assigning variable denom");
    current_statement__ = 102;
    return stan::math::elt_divide(factor, denom);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T3__>,-1,1>
diagSPD_EQ(const T0__& alpha, const T1__& rho, const int& M, const T3__& L,
           std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 104;
    stan::math::validate_non_negative_index("indices", "M", M);
    Eigen::Matrix<local_scalar_t__,-1,1> indices =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
    current_statement__ = 105;
    stan::model::assign(indices, stan::math::linspaced_vector(M, 1, M),
      "assigning variable indices");
    local_scalar_t__ factor = DUMMY_VAR__;
    current_statement__ = 106;
    factor = (alpha *
      stan::math::sqrt((stan::math::sqrt((2 * stan::math::pi())) * rho)));
    local_scalar_t__ exponent = DUMMY_VAR__;
    current_statement__ = 107;
    exponent = (-0.25 *
      stan::math::pow((((rho * stan::math::pi()) / 2) / L), 2));
    current_statement__ = 108;
    return stan::math::multiply(factor,
             stan::math::exp(
               stan::math::multiply(exponent, stan::math::square(indices))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_hsgp_updated final : public model_base_crtp<model_hsgp_updated> {
private:
  int S;
  int N_total;
  int M;
  double mu_rho_pop;
  double mu_rho_subj;
  double L_factor;
  Eigen::Matrix<double,-1,1> t_ev_data__;
  Eigen::Matrix<double,-1,1> dt_data__;
  std::vector<int> s_id;
  double L;
  Eigen::Matrix<double,-1,1> qx_data__;
  Eigen::Matrix<double,-1,1> qw_data__;
  Eigen::Matrix<double,-1,1> log_qw_data__;
  std::vector<Eigen::Matrix<double,-1,-1>> PHI_quad;
  int z_subj_raw_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_ev{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> dt{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> qx{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> qw{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_qw{nullptr, 0};
public:
  ~model_hsgp_updated() {}
  model_hsgp_updated(stan::io::var_context& context__, unsigned int
                     random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_hsgp_updated_namespace::model_hsgp_updated";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 46;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 46;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "N_total", "int",
        std::vector<size_t>{});
      N_total = std::numeric_limits<int>::min();
      current_statement__ = 47;
      N_total = context__.vals_i("N_total")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "N_total", N_total, 1);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 48;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "M", M, 1);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "mu_rho_pop", "double",
        std::vector<size_t>{});
      mu_rho_pop = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      mu_rho_pop = context__.vals_r("mu_rho_pop")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "mu_rho_pop",
        mu_rho_pop, 0);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "mu_rho_subj", "double",
        std::vector<size_t>{});
      mu_rho_subj = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 50;
      mu_rho_subj = context__.vals_r("mu_rho_subj")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "mu_rho_subj",
        mu_rho_subj, 0);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "L_factor", "double",
        std::vector<size_t>{});
      L_factor = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 51;
      L_factor = context__.vals_r("L_factor")[(1 - 1)];
      current_statement__ = 51;
      stan::math::check_greater_or_equal(function__, "L_factor", L_factor, 0);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("t_ev", "N_total", N_total);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "t_ev", "double",
        std::vector<size_t>{static_cast<size_t>(N_total)});
      t_ev_data__ = Eigen::Matrix<double,-1,1>::Constant(N_total,
                      std::numeric_limits<double>::quiet_NaN());
      new (&t_ev) Eigen::Map<Eigen::Matrix<double,-1,1>>(t_ev_data__.data(),
        N_total);
      {
        std::vector<local_scalar_t__> t_ev_flat__;
        current_statement__ = 53;
        t_ev_flat__ = context__.vals_r("t_ev");
        current_statement__ = 53;
        pos__ = 1;
        current_statement__ = 53;
        for (int sym1__ = 1; sym1__ <= N_total; ++sym1__) {
          current_statement__ = 53;
          stan::model::assign(t_ev, t_ev_flat__[(pos__ - 1)],
            "assigning variable t_ev", stan::model::index_uni(sym1__));
          current_statement__ = 53;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 54;
      stan::math::validate_non_negative_index("dt", "N_total", N_total);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "dt", "double",
        std::vector<size_t>{static_cast<size_t>(N_total)});
      dt_data__ = Eigen::Matrix<double,-1,1>::Constant(N_total,
                    std::numeric_limits<double>::quiet_NaN());
      new (&dt) Eigen::Map<Eigen::Matrix<double,-1,1>>(dt_data__.data(),
        N_total);
      {
        std::vector<local_scalar_t__> dt_flat__;
        current_statement__ = 55;
        dt_flat__ = context__.vals_r("dt");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= N_total; ++sym1__) {
          current_statement__ = 55;
          stan::model::assign(dt, dt_flat__[(pos__ - 1)],
            "assigning variable dt", stan::model::index_uni(sym1__));
          current_statement__ = 55;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 56;
      stan::math::validate_non_negative_index("s_id", "N_total", N_total);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "s_id", "int",
        std::vector<size_t>{static_cast<size_t>(N_total)});
      s_id = std::vector<int>(N_total, std::numeric_limits<int>::min());
      current_statement__ = 57;
      s_id = context__.vals_i("s_id");
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "s_id", s_id, 1);
      current_statement__ = 57;
      stan::math::check_less_or_equal(function__, "s_id", s_id, S);
      current_statement__ = 58;
      L = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 58;
      L = (L_factor * stan::math::max(t_ev));
      current_statement__ = 59;
      qx_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                    std::numeric_limits<double>::quiet_NaN());
      new (&qx) Eigen::Map<Eigen::Matrix<double,-1,1>>(qx_data__.data(), 3);
      current_statement__ = 59;
      stan::model::assign(qx,
        (Eigen::Matrix<double,-1,1>(3) << 0.1127016654, 0.5, 0.8872983346).finished(),
        "assigning variable qx");
      current_statement__ = 60;
      qw_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                    std::numeric_limits<double>::quiet_NaN());
      new (&qw) Eigen::Map<Eigen::Matrix<double,-1,1>>(qw_data__.data(), 3);
      current_statement__ = 60;
      stan::model::assign(qw,
        (Eigen::Matrix<double,-1,1>(3) << (5.0 / 18.0), (8.0 / 18.0), (5.0 /
                                         18.0)).finished(),
        "assigning variable qw");
      current_statement__ = 61;
      log_qw_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                        std::numeric_limits<double>::quiet_NaN());
      new (&log_qw)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_qw_data__.data(), 3);
      current_statement__ = 61;
      stan::model::assign(log_qw, stan::math::log(qw),
        "assigning variable log_qw");
      current_statement__ = 62;
      stan::math::validate_non_negative_index("PHI_quad", "N_total", N_total);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("PHI_quad", "M", M);
      current_statement__ = 64;
      PHI_quad = std::vector<Eigen::Matrix<double,-1,-1>>(3,
                   Eigen::Matrix<double,-1,-1>::Constant(N_total, M,
                     std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 69;
      for (int j = 1; j <= 3; ++j) {
        current_statement__ = 65;
        stan::math::validate_non_negative_index("t_quad", "N_total", N_total);
        Eigen::Matrix<double,-1,1> t_quad =
          Eigen::Matrix<double,-1,1>::Constant(N_total,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 66;
        stan::model::assign(t_quad,
          stan::math::subtract(t_ev,
            stan::math::elt_multiply((1.0 -
              stan::model::rvalue(qx, "qx", stan::model::index_uni(j))), dt)),
          "assigning variable t_quad");
        current_statement__ = 67;
        stan::model::assign(PHI_quad, phi(N_total, M, L, t_quad, pstream__),
          "assigning variable PHI_quad", stan::model::index_uni(j));
      }
      current_statement__ = 70;
      stan::math::validate_non_negative_index("z_pop", "M", M);
      current_statement__ = 71;
      z_subj_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 71;
      z_subj_raw_1dim__ = (S - 1);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("z_subj_raw", "S - 1",
        z_subj_raw_1dim__);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("z_subj_raw", "M", M);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("mu", "S", S);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("z_subj", "S", S);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("z_subj", "M", M);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("diag_S_pop", "M", M);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("diag_S_subj", "M", M);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("spectral_pop", "M", M);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("beta_subj", "S", S);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("beta_subj", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = M + 1 + 1 + (z_subj_raw_1dim__ * M) + 1 + 1 + S + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_hsgp_updated";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_hsgp_updated_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> z_pop =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 1;
      z_pop = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M);
      local_scalar_t__ rho_pop = DUMMY_VAR__;
      current_statement__ = 2;
      rho_pop = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      local_scalar_t__ alpha_pop = DUMMY_VAR__;
      current_statement__ = 3;
      alpha_pop = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_subj_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(z_subj_raw_1dim__, M,
          DUMMY_VAR__);
      current_statement__ = 4;
      z_subj_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(z_subj_raw_1dim__,
                     M);
      local_scalar_t__ rho_subj = DUMMY_VAR__;
      current_statement__ = 5;
      rho_subj = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      local_scalar_t__ alpha_subj = DUMMY_VAR__;
      current_statement__ = 6;
      alpha_subj = in__.template read_constrain_lb<local_scalar_t__,
                     jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 7;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(S);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 8;
      k = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(1,
            lp__);
      local_scalar_t__ lambda_shape = DUMMY_VAR__;
      current_statement__ = 9;
      lambda_shape = in__.template read_constrain_lb<local_scalar_t__,
                       jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_subj =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, M, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> diag_S_pop =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(diag_S_pop,
        diagSPD_EQ(alpha_pop, rho_pop, M, L, pstream__),
        "assigning variable diag_S_pop");
      Eigen::Matrix<local_scalar_t__,-1,1> diag_S_subj =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(diag_S_subj,
        diagSPD_EQ(alpha_subj, rho_subj, M, L, pstream__),
        "assigning variable diag_S_subj");
      current_statement__ = 15;
      stan::model::assign(z_subj, z_subj_raw, "assigning variable z_subj",
        stan::model::index_min_max(1, (S - 1)), stan::model::index_omni());
      current_statement__ = 18;
      for (int m = 1; m <= M; ++m) {
        current_statement__ = 16;
        stan::model::assign(z_subj,
          -stan::math::sum(
             stan::model::rvalue(z_subj_raw, "z_subj_raw",
               stan::model::index_omni(), stan::model::index_uni(m))),
          "assigning variable z_subj", stan::model::index_uni(S),
          stan::model::index_uni(m));
      }
      Eigen::Matrix<local_scalar_t__,-1,1> spectral_pop =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 13;
      stan::model::assign(spectral_pop,
        stan::math::elt_multiply(diag_S_pop, z_pop),
        "assigning variable spectral_pop");
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_subj =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, M, DUMMY_VAR__);
      current_statement__ = 14;
      stan::model::assign(beta_subj,
        stan::math::diag_post_multiply(z_subj, diag_S_subj),
        "assigning variable beta_subj");
      {
        current_statement__ = 19;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z_pop));
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::math::to_vector(z_subj_raw), 0,
                         stan::math::sqrt((1.0 - (1.0 / S)))));
        current_statement__ = 21;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(rho_pop,
                         mu_rho_pop, 0.8));
        current_statement__ = 22;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(rho_subj,
                         mu_rho_subj, 0.8));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha_pop, 0.5, 0.3));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha_subj, 0.5, 0.3));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, 2, 1));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(lambda_shape, 0.5,
                         0.2));
        current_statement__ = 27;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(k, lambda_shape));
        current_statement__ = 28;
        if (stan::math::logical_lt(k, 1)) {
          current_statement__ = 28;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 28;
          lp_accum__.add(-stan::math::exponential_lccdf(1, lambda_shape));
        }
        current_statement__ = 29;
        stan::math::validate_non_negative_index("eta_quad", "N_total",
          N_total);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> eta_quad =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(3,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_total,
              DUMMY_VAR__));
        current_statement__ = 37;
        for (int j = 1; j <= 3; ++j) {
          current_statement__ = 31;
          stan::math::validate_non_negative_index("f_pop", "N_total", N_total);
          Eigen::Matrix<local_scalar_t__,-1,1> f_pop =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_total,
              DUMMY_VAR__);
          current_statement__ = 32;
          stan::model::assign(f_pop,
            stan::math::multiply(
              stan::model::rvalue(PHI_quad, "PHI_quad",
                stan::model::index_uni(j)), spectral_pop),
            "assigning variable f_pop");
          current_statement__ = 33;
          stan::math::validate_non_negative_index("f_subj", "N_total",
            N_total);
          Eigen::Matrix<local_scalar_t__,-1,1> f_subj =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_total,
              DUMMY_VAR__);
          current_statement__ = 34;
          stan::model::assign(f_subj,
            stan::math::rows_dot_product(
              stan::model::rvalue(PHI_quad, "PHI_quad",
                stan::model::index_uni(j)),
              stan::model::rvalue(beta_subj, "beta_subj",
                stan::model::index_multi(s_id), stan::model::index_omni())),
            "assigning variable f_subj");
          current_statement__ = 35;
          stan::model::assign(eta_quad,
            stan::math::add(
              stan::math::add(
                stan::model::rvalue(mu, "mu", stan::model::index_multi(s_id)),
                f_pop), f_subj), "assigning variable eta_quad",
            stan::model::index_uni(j));
        }
        current_statement__ = 45;
        for (int n = 1; n <= N_total; ++n) {
          Eigen::Matrix<local_scalar_t__,-1,1> log_kernel =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__);
          current_statement__ = 42;
          for (int j = 1; j <= 3; ++j) {
            local_scalar_t__ theta = DUMMY_VAR__;
            current_statement__ = 39;
            theta = stan::math::exp(
                      -stan::model::rvalue(
                         stan::model::rvalue(eta_quad, "eta_quad",
                           stan::model::index_uni(j)), "eta_quad[j]",
                         stan::model::index_uni(n)));
            current_statement__ = 40;
            stan::model::assign(log_kernel,
              (stan::model::rvalue(log_qw, "log_qw",
                 stan::model::index_uni(j)) +
              stan::math::gamma_lpdf<false>(
                stan::model::rvalue(dt, "dt", stan::model::index_uni(n)), k,
                theta)), "assigning variable log_kernel",
              stan::model::index_uni(j));
          }
          current_statement__ = 43;
          lp_accum__.add(stan::math::log_sum_exp(log_kernel));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_hsgp_updated_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> z_pop =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      z_pop = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M);
      double rho_pop = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      rho_pop = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      double alpha_pop = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      alpha_pop = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,-1> z_subj_raw =
        Eigen::Matrix<double,-1,-1>::Constant(z_subj_raw_1dim__, M,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      z_subj_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(z_subj_raw_1dim__,
                     M);
      double rho_subj = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      rho_subj = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      double alpha_subj = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      alpha_subj = in__.template read_constrain_lb<local_scalar_t__,
                     jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(S,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(S);
      double k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      k = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(1,
            lp__);
      double lambda_shape = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      lambda_shape = in__.template read_constrain_lb<local_scalar_t__,
                       jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,-1> z_subj =
        Eigen::Matrix<double,-1,-1>::Constant(S, M,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> diag_S_pop =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> diag_S_subj =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> spectral_pop =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> beta_subj =
        Eigen::Matrix<double,-1,-1>::Constant(S, M,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(z_pop);
      out__.write(rho_pop);
      out__.write(alpha_pop);
      out__.write(z_subj_raw);
      out__.write(rho_subj);
      out__.write(alpha_subj);
      out__.write(mu);
      out__.write(k);
      out__.write(lambda_shape);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 11;
      stan::model::assign(diag_S_pop,
        diagSPD_EQ(alpha_pop, rho_pop, M, L, pstream__),
        "assigning variable diag_S_pop");
      current_statement__ = 12;
      stan::model::assign(diag_S_subj,
        diagSPD_EQ(alpha_subj, rho_subj, M, L, pstream__),
        "assigning variable diag_S_subj");
      current_statement__ = 15;
      stan::model::assign(z_subj, z_subj_raw, "assigning variable z_subj",
        stan::model::index_min_max(1, (S - 1)), stan::model::index_omni());
      current_statement__ = 18;
      for (int m = 1; m <= M; ++m) {
        current_statement__ = 16;
        stan::model::assign(z_subj,
          -stan::math::sum(
             stan::model::rvalue(z_subj_raw, "z_subj_raw",
               stan::model::index_omni(), stan::model::index_uni(m))),
          "assigning variable z_subj", stan::model::index_uni(S),
          stan::model::index_uni(m));
      }
      current_statement__ = 13;
      stan::model::assign(spectral_pop,
        stan::math::elt_multiply(diag_S_pop, z_pop),
        "assigning variable spectral_pop");
      current_statement__ = 14;
      stan::model::assign(beta_subj,
        stan::math::diag_post_multiply(z_subj, diag_S_subj),
        "assigning variable beta_subj");
      if (emit_transformed_parameters__) {
        out__.write(z_subj);
        out__.write(diag_S_pop);
        out__.write(diag_S_subj);
        out__.write(spectral_pop);
        out__.write(beta_subj);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> z_pop =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(z_pop,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(M),
        "assigning variable z_pop");
      out__.write(z_pop);
      local_scalar_t__ rho_pop = DUMMY_VAR__;
      current_statement__ = 2;
      rho_pop = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, rho_pop);
      local_scalar_t__ alpha_pop = DUMMY_VAR__;
      current_statement__ = 3;
      alpha_pop = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha_pop);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_subj_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(z_subj_raw_1dim__, M,
          DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(z_subj_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(z_subj_raw_1dim__,
          M), "assigning variable z_subj_raw");
      out__.write(z_subj_raw);
      local_scalar_t__ rho_subj = DUMMY_VAR__;
      current_statement__ = 5;
      rho_subj = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, rho_subj);
      local_scalar_t__ alpha_subj = DUMMY_VAR__;
      current_statement__ = 6;
      alpha_subj = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha_subj);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(S),
        "assigning variable mu");
      out__.write(mu);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 8;
      k = in__.read<local_scalar_t__>();
      out__.write_free_lb(1, k);
      local_scalar_t__ lambda_shape = DUMMY_VAR__;
      current_statement__ = 9;
      lambda_shape = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, lambda_shape);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "z_pop", "double",
        std::vector<size_t>{static_cast<size_t>(M)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "rho_pop",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "alpha_pop",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "z_subj_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(z_subj_raw_1dim__),
          static_cast<size_t>(M)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "rho_subj",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "alpha_subj",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(S)});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "k", "double",
        std::vector<size_t>{});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "lambda_shape",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> z_pop =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_pop_flat__;
        current_statement__ = 1;
        z_pop_flat__ = context__.vals_r("z_pop");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(z_pop, z_pop_flat__[(pos__ - 1)],
            "assigning variable z_pop", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z_pop);
      local_scalar_t__ rho_pop = DUMMY_VAR__;
      current_statement__ = 2;
      rho_pop = context__.vals_r("rho_pop")[(1 - 1)];
      out__.write_free_lb(0, rho_pop);
      local_scalar_t__ alpha_pop = DUMMY_VAR__;
      current_statement__ = 3;
      alpha_pop = context__.vals_r("alpha_pop")[(1 - 1)];
      out__.write_free_lb(0, alpha_pop);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_subj_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(z_subj_raw_1dim__, M,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_subj_raw_flat__;
        current_statement__ = 4;
        z_subj_raw_flat__ = context__.vals_r("z_subj_raw");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= z_subj_raw_1dim__; ++sym2__) {
            current_statement__ = 4;
            stan::model::assign(z_subj_raw, z_subj_raw_flat__[(pos__ - 1)],
              "assigning variable z_subj_raw",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(z_subj_raw);
      local_scalar_t__ rho_subj = DUMMY_VAR__;
      current_statement__ = 5;
      rho_subj = context__.vals_r("rho_subj")[(1 - 1)];
      out__.write_free_lb(0, rho_subj);
      local_scalar_t__ alpha_subj = DUMMY_VAR__;
      current_statement__ = 6;
      alpha_subj = context__.vals_r("alpha_subj")[(1 - 1)];
      out__.write_free_lb(0, alpha_subj);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 7;
        mu_flat__ = context__.vals_r("mu");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 7;
          stan::model::assign(mu, mu_flat__[(pos__ - 1)],
            "assigning variable mu", stan::model::index_uni(sym1__));
          current_statement__ = 7;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(mu);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 8;
      k = context__.vals_r("k")[(1 - 1)];
      out__.write_free_lb(1, k);
      local_scalar_t__ lambda_shape = DUMMY_VAR__;
      current_statement__ = 9;
      lambda_shape = context__.vals_r("lambda_shape")[(1 - 1)];
      out__.write_free_lb(0, lambda_shape);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"z_pop", "rho_pop", "alpha_pop",
                "z_subj_raw", "rho_subj", "alpha_subj", "mu", "k",
                "lambda_shape"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"z_subj", "diag_S_pop", "diag_S_subj", "spectral_pop",
             "beta_subj"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(M)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(z_subj_raw_1dim__),
                  static_cast<size_t>(M)}, std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(S)},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(M)},
             std::vector<size_t>{static_cast<size_t>(M)},
             std::vector<size_t>{static_cast<size_t>(M)},
             std::vector<size_t>{static_cast<size_t>(M)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(M)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_pop" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho_pop");
    param_names__.emplace_back(std::string() + "alpha_pop");
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= z_subj_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_subj_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "rho_subj");
    param_names__.emplace_back(std::string() + "alpha_subj");
    for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "lambda_shape");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "z_subj" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "diag_S_pop" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "diag_S_subj" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "spectral_pop" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_subj" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_pop" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho_pop");
    param_names__.emplace_back(std::string() + "alpha_pop");
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= z_subj_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_subj_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "rho_subj");
    param_names__.emplace_back(std::string() + "alpha_subj");
    for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "lambda_shape");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "z_subj" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "diag_S_pop" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "diag_S_subj" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        param_names__.emplace_back(std::string() + "spectral_pop" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_subj" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"z_pop\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"rho_pop\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha_pop\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_subj_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(z_subj_raw_1dim__) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"rho_subj\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha_subj\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda_shape\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_subj\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"diag_S_pop\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"diag_S_subj\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"spectral_pop\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_subj\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"z_pop\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"rho_pop\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha_pop\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_subj_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(z_subj_raw_1dim__) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"rho_subj\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha_subj\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda_shape\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_subj\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"diag_S_pop\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"diag_S_subj\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"spectral_pop\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_subj\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((M + 1) + 1) + (z_subj_raw_1dim__ *
      M)) + 1) + 1) + S) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((((S * M)
      + M) + M) + M) + (S * M)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((M + 1) + 1) + (z_subj_raw_1dim__ *
      M)) + 1) + 1) + S) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((((S * M)
      + M) + M) + M) + (S * M)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_hsgp_updated_namespace::model_hsgp_updated;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_hsgp_updated_namespace::profiles__;
}
#endif
#endif
